groups:
  - name: edge
    interval: 1m
    rules:
      - record: edge:requests:rate5m
        expr: |
          sum by (host) (
            rate({service="central-ingress"} | json | logger =~ `http\.log\.access.*` | label_format host=request_host [5m])
          )

      - record: edge:requests_5xx:rate5m
        expr: |
          sum by (host) (
            rate({service="central-ingress"} | json | logger =~ `http\.log\.access.*` | status >= 500 | label_format host=request_host [5m])
          )

      - record: edge:latency_p95_seconds:5m
        expr: |
          quantile_over_time(0.95,
            {service="central-ingress"} | json | logger =~ `http\.log\.access.*` | label_format host=request_host | unwrap duration [5m]
          ) by (host)
